units: samples.tsv        # Complete the tab sep value file with the path to the files and their conditions

### Definition of the path Snakemake has to create
working_dir: "temp/"
result_dir: "results/"

### Genome and annotations
refs:
  genome:
    "ftp://ftp.solgenomics.net/genomes/Petunia_axillaris/assembly/Petunia_axillaris_v1.6.2_genome.fasta"

### Software parameters
fastp:
  qualified_quality_phred: 15 # the quality value that a base is qualified. Default 15 means phred quality >=Q15 is qualified. (int [=15])